### ISSUE TITLE
Google submission failed due to robolectric SDK

### ISSUE THREAD

**Issue by elieT27** [audienzz/react-native-audienzz#22]
We are experiencing a huge issue, Google has declined the submission of our react native application. 

Audienzz is using this SDK [https://github.com/robolectric/robolectric](url) which is non-compliant for Google. 

Here is google's response : "We examined the SDKs used by your application and found non-compliant versions of SDKs that contain code to download, executable code (e.g. dex, JAR, so files) from a source other than Google Play. 

We made an appeal but Google is telling us that  the package robolectric needs to be removed or else our app will not be approved.

 Can you make an update ASAP so we can keep using your SDK

**Comment by alex-ragin** [comment]
Hi @elieT27,

Thanks for letting us know. Our team is on it.

**Comment by alex-ragin** [comment]
Hi @elieT27,

Please try to use the latest version, 0.5.4.

We applied a temporary fix by removing the Robolectric from the AppNexus SDK.

Ensure you run `./gradlew clean` before generating a bundle or an APK.
