### ISSUE TITLE
Wrong UserAgent iOS at launch

### ISSUE THREAD

**Issue by huextrat** [audienzz/react-native-audienzz#3]
Only on iOS, the UserAgent is not correctly set at first launch. 

We have a call to `mediation.adnxs.com` with this kind of UserAgent `APP_NAME CFNetwork/1327.0.4 Darwin/21.2.0` when we should have something like this `Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148` which is correct for the next ad loaded in the application.

The issue was also present in the previous version : https://www.npmjs.com/package/audienzz-rn-sdk

I looked in the JS code I didn't find anything related to the UserAgent maybe this is due to the native iOS code?

**Comment by alex-ragin** [comment]
Thanks for that, good catch! We'll check this out, however, native requests are done via AppNexus SDK. We'll contact the AppNexus team in case we cannot fix that on our side.

**Comment by alex-ragin** [comment]
The bug has been fixed in 0.4.2.
