### ISSUE TITLE
Wrong sizes type

### ISSUE THREAD

**Issue by huextrat** [audienzz/react-native-audienzz#4]
Hi,

After an investigation on a typescript error that I pass several sizes on the parameter sizes I noticed that the type was wrong when passing an array in this kind: 
```
[[320, 460], [320, 480]]
```

The type should be `number[][]` instead of `[[number, number]]` right ?

https://github.com/audienzzag/react-native-audienzz/blob/379f7739a3ac26be566a91e23bd6d55fed064924/src/AppNexusBanner/AppNexusBanner.tsx#L38

**Comment by alex-ragin** [comment]
Hi, @huextrat thanks for the issue! We'll update the lib with a fix in a couple of days.

**Comment by huextrat** [comment]
Solved in the latest release (v4.0.1). Thx @alex-ragin
