### ISSUE TITLE
PERCENT_VISIBILITY issue on Android

### ISSUE THREAD

**Issue by huextrat** [audienzz/react-native-audienzz#5]
Hi,

Here is a new major issue when building on Android : `PERCENT_VISIBILITY` is not existing in `Constants.java`

https://github.com/audienzz/react-native-audienzz/blob/b38afcf80dd5bc4041b95f8b06ee69cbe0647dea/android/src/main/java/com/reactnativeaudienzz/RTCAppNexusBanner.java#L11

**Comment by alexeyzolotaryov** [comment]
Hi
Thanks for finding the problem. Fixed
