### ISSUE TITLE
Ads not showing with release over 0.4.2

### ISSUE THREAD

**Issue by Lucile-Peltier** [audienzz/react-native-audienzz#9]
Hi, 
We are using your library with the version 0.4.2 and it is working (ads are present in the app). But when I update the library version with the 0.4.3 or the 0.4.4 they don't anymore. 
Is it a known issue ?

**Comment by BuniEmris** [comment]
Hi, @Lucile-Peltier  thanks for the issue! The bug has been fixed in release (0.5.0). Please check the latest version
